name: ci

on:
  workflow_dispatch:
    inputs:
      buildx-version:
        required: false
      buildx-driver-opts:
        required: false
        default: 'image=moby/buildkit:master'
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@master
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          version: ${{ github.event.inputs.buildx-version }}
          driver-opts: ${{ github.event.inputs.buildx-driver-opts }}
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Build
        uses: docker/build-push-action@master
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: false
          tags: |
            name/app:latest
            name/app:1.0.0
