name: containerd

on:
  workflow_dispatch:
  push:
    branches: master
    tags:
      - 'v*.*.*'
  pull_request:
    branches: master

env:
  CONTAINERD_VERSION: 1.4.1

jobs:
  github-ghcr:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/crazy-max/test-docker-action-containerd
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          driver-opts: network=host,image=moby/buildkit:master
      -
        name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v1
      -
        name: Build
        uses: docker/build-push-action@master
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          tags: ${{ steps.docker_meta.outputs.tags }}
          outputs: type=oci,dest=/tmp/image.tar
      -
        name: Import image in Containerd
        run: |
          sudo ctr --debug image import --base-name ${{ steps.prep.outputs.docker_image }} --digests --all-platforms /tmp/image.tar
      -
        name: List Containerd images
        run: |
          sudo ctr image ls
      -
        name: Push image with Containerd
        run: |
          #sudo ctr --debug image push --user "${{ github.repository_owner }}:${{ secrets.CR_PAT }}" ${{ steps.prep.outputs.docker_image }}:${{ steps.prep.outputs.version }}
