name: digest

on:
  workflow_dispatch:
  push:
    branches: master
    tags:
      - 'v*.*.*'
  pull_request:
    branches: master

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Daemon config
        run: |
          sudo cat /etc/docker/daemon.json
      -
        name: Preload images
        run: |
          docker image ls
      -
        name: Networks
        run: |
          docker network inspect $(docker network ls -q)
      -
        name: Build
        uses: docker/build-push-action@master
        with:
          context: .
          file: ./digest.Dockerfile
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
