name: docker-driver

on:
  workflow_dispatch:
    inputs:
      build-push-version:
        required: false
        default: 'master'
      buildx-version:
        required: false
      buildx-driver-opts:
        required: false
  push:
    branches: master
    tags:
      - 'v*.*.*'
  pull_request:
    branches: master

jobs:
  push:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        uses: docker/build-push-action@${{ github.event.inputs.build-push-version }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: localhost:5000/name/app:latest
