name: docker-driver

on:
  workflow_dispatch:
    inputs:
      buildx-version:
        description: 'Buildx version (eg. v0.3.0, latest)'
        required: false
      buildx-driver-opts:
        description: 'List of additional driver-specific options (eg. image=moby/buildkit:master)'
        required: false
  push:
    branches: master
    tags:
      - 'v*.*.*'
  pull_request:
    branches: master

jobs:
  push:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: localhost:5000/name/app:latest
