name: event

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  release:
    types: [ published ]
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:

jobs:
  event:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Event
        run: |
          cat $GITHUB_EVENT_PATH
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
