name: full

on:
  workflow_dispatch:
    inputs:
      build-push-version:
        required: false
        default: 'master'
      buildx-version:
        required: false
      buildx-driver-opts:
        required: false
  push:
    branches: master
    tags:
      - 'v*.*.*'
  pull_request:
    branches: master

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - registry: ''
            image: crazymax/test-docker-action
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
          - registry: ghcr.io
            image: ghcr.io/crazymax/test-docker-action
            username: ${{ github.repository_owner }}
            password: ${{ secrets.CR_PAT }}
          - registry: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            image: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/test-docker-action
            username: ${{ secrets.AWS_ACCESS_KEY_ID }}
            password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ matrix.image }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: ${{ github.event.inputs.buildx-version }}
          driver-opts: ${{ github.event.inputs.buildx-driver-opts }}
      -
        name: Login to Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ matrix.image }}
          username: ${{ matrix.username }}
          password: ${{ matrix.password }}
      -
        name: Build
        uses: docker/build-push-action@${{ github.event.inputs.build-push-version }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          labels: ${{ steps.prep.outputs.labels }}
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
