name: login

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  dockerhub:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
        logout:
          - true
          - false
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: ${{ matrix.logout }}
      -
        name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json

  ghcr:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        logout:
          - true
          - false
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.2
      -
        name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: ${{ matrix.logout }}
      -
        name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json

  gitlab:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        logout:
          - true
          - false
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.2
      -
        name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}
          logout: ${{ matrix.logout }}
      -
        name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json

  ecr:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
        logout:
          - true
          - false
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.1
      -
        name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          logout: ${{ matrix.logout }}
      -
        name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
