name: miss-cache

on:
  workflow_dispatch:
  push:
    branches: master
    tags:
      - 'v*.*.*'
  pull_request:
    branches: master

jobs:
  git-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.miss-cache
          key: ${{ runner.os }}-miss-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-miss-cache-
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          target: build
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          cache-from: type=local,src=/tmp/.miss-cache
          cache-to: type=local,dest=/tmp/.miss-cache
