name: secret

on:
  workflow_dispatch:
    inputs:
      buildx-version:
        description: 'Buildx version (eg. v0.3.0, latest)'
        required: false
      buildx-driver-opts:
        description: 'List of additional driver-specific options (eg. image=moby/buildkit:master)'
        required: false
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  multiline:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: ${{ inputs.buildx-version }}
          driver-opts: ${{ inputs.buildx-driver-opts }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          secrets: |
            "MULTILINE=${{ secrets.MULTILINE_SECRET }}"
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
