name: secret

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  multiline:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          secrets: |
            MULTILINE=${{ secrets.MULTILINE_SECRET }}
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
