name: shared-jobs

on:
  workflow_dispatch:
    inputs:
      buildx-version:
        description: 'Buildx version (eg. v0.3.0, latest)'
        required: false
      buildx-driver-opts:
        description: 'List of additional driver-specific options (eg. image=moby/buildkit:master)'
        required: false
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: ${{ github.event.inputs.buildx-version }}
          driver-opts: ${{ github.event.inputs.buildx-driver-opts }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: myimage:latest
          outputs: type=docker,dest=/tmp/myimage.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: myimage
          path: /tmp/myimage.tar
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: ${{ github.event.inputs.buildx-version }}
          driver-opts: ${{ github.event.inputs.buildx-driver-opts }}
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: myimage
          path: /tmp
      -
        name: Load Docker image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
