name: test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        run: |
          sudo find / -type f -name "config.json"
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
